import { lib } from '@nr6/nand2tetris-logic-gates'

export const DEFAULT_BLANK_CHIP = {
  id: 0,
  name: '',
  description: '',
  truthTable: [],
  inputs: [],
  outputs: [],
}

export const DEFAULT_CHIPS = {
  1: {
    name: 'ID',
    description: 'Outputs the same value as the input.',
    functionality: lib.ID,
    truthTable: [
      ['in', 'out'],
      [0, 0],
      [1, 1],
    ],
    inputs: ['in'],
    outputs: ['out'],
    id: 1,
  },
  2: {
    name: 'NAND',
    description: 'Outputs true unless both inputs are true',
    functionality: lib.NAND,
    truthTable: [
      ['a', 'b', 'out'],
      [0, 0, 1],
      [0, 1, 1],
      [1, 0, 1],
      [1, 1, 0],
    ],
    inputs: ['a', 'b'],
    outputs: ['out'],
    id: 2,
  },
  3: {
    name: 'NOT',
    description: 'Outputs true if the input it false and false if the input is true.',
    functionality: lib.NOT,
    truthTable: [
      ['in', 'out'],
      [0, 1],
      [1, 0],
    ],
    inputs: ['in'],
    outputs: ['out'],
    id: 3,
  },
  4: {
    name: 'AND',
    description: 'Outputs true if both inputs are true.',
    functionality: lib.AND,
    truthTable: [
      ['a', 'b', 'out'],
      [0, 0, 0],
      [0, 1, 0],
      [1, 0, 0],
      [1, 1, 1],
    ],
    inputs: ['a', 'b'],
    outputs: ['out'],
    id: 4,
  },
  5: {
    name: 'OR',
    description: 'Outputs true if either input is true.',
    functionality: lib.OR,
    truthTable: [
      ['a', 'b', 'out'],
      [0, 0, 0],
      [0, 1, 1],
      [1, 0, 1],
      [1, 1, 1],
    ],
    inputs: ['a', 'b'],
    outputs: ['out'],
    id: 5,
  },
  6: {
    name: 'MUX',
    description: 'Outputs the value of a if sel is false, otherwise it outputs the value of b.',
    functionality: lib.MUX,
    truthTable: [
      ['a', 'b', 'sel', 'out'],
      [0, 0, 0, 0],
      [0, 0, 1, 0],
      [0, 1, 0, 0],
      [0, 1, 1, 1],
      [1, 0, 0, 1],
      [1, 0, 1, 0],
      [1, 1, 0, 1],
      [1, 1, 1, 1],
    ],
    inputs: ['a', 'b', 'sel'],
    outputs: ['out'],
    id: 6,
  },
  7: {
    name: 'DMUX',
    description: 'Output a equals the input value if sel is false, otherwise output b equals the input value.',
    functionality: lib.DMUX,
    truthTable: [
      ['in', 'sel', 'a', 'b'],
      [0, 0, 0, 0],
      [0, 1, 0, 0],
      [1, 0, 1, 0],
      [1, 1, 0, 1],
    ],
    inputs: ['in', 'sel'],
    outputs: ['a', 'b'],
    id: 7,
  },
}
